2021-12-10 12:11:40.968 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.059 [main] INFO  org.example.App - Records were selected
2021-12-10 12:11:41.067 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.077 [main] INFO  org.example.App - Records were selected
2021-12-10 12:11:41.079 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.087 [main] INFO  org.example.App - Records were selected
2021-12-10 12:11:41.088 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.094 [main] INFO  org.example.App - Records were selected
2021-12-10 12:11:41.094 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.102 [main] INFO  org.example.App - Records were selected
2021-12-10 12:11:41.139 [main] INFO  org.example.App - {"id":1639127501080,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:11:41","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:11:41.451 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:11:41.546 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:11:41.549 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:11:41.577 [main] INFO  org.example.App - New History record added
2021-12-10 12:11:41.578 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:11:41.578 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.588 [main] INFO  org.example.App - All records were added
2021-12-10 12:11:41.589 [main] INFO  org.example.App - {"id":1639127501580,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:11:41","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:11:41.591 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:11:41.600 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:11:41.600 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:11:41.601 [main] INFO  org.example.App - New History record added
2021-12-10 12:11:41.604 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.623 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:11:41.624 [main] INFO  org.example.App - {"id":1639127501605,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:11:41","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1638871430803,\"name\":\"Ahalab\",\"surname\":\"surname1\"}","status":"SUCCESS"}
2021-12-10 12:11:41.626 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:11:41.636 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:11:41.636 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:11:41.637 [main] INFO  org.example.App - New History record added
2021-12-10 12:11:41.638 [main] INFO  org.example.App - {"id":1639127501063,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:11:41","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:11:41.640 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:11:41.651 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:11:41.651 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:11:41.652 [main] INFO  org.example.App - New History record added
2021-12-10 12:11:41.653 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:11:41.653 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:11:41.660 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.503 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.601 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.607 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.615 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.617 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.623 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.623 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.631 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.631 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.637 [main] INFO  org.example.App - Records were selected
2021-12-10 12:12:25.665 [main] INFO  org.example.App - {"id":1639127545618,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:12:25","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:12:25.886 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:12:25.919 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:12:25.922 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:12:25.934 [main] INFO  org.example.App - New History record added
2021-12-10 12:12:25.935 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:12:25.935 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.944 [main] INFO  org.example.App - All records were added
2021-12-10 12:12:25.944 [main] INFO  org.example.App - {"id":1639127545937,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:12:25","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:12:25.947 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:12:25.954 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:12:25.955 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:12:25.956 [main] INFO  org.example.App - New History record added
2021-12-10 12:12:25.958 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.961 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:12:25.961 [main] INFO  org.example.App - {"id":1639127545959,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:12:25","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1638871430803,\"name\":\"Ahalab\",\"surname\":\"surname2\"}","status":"SUCCESS"}
2021-12-10 12:12:25.964 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:12:25.973 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:12:25.974 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:12:25.974 [main] INFO  org.example.App - New History record added
2021-12-10 12:12:25.975 [main] INFO  org.example.App - {"id":1639127545604,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:12:25","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:12:25.976 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:12:25.983 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:12:25.983 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:12:25.984 [main] INFO  org.example.App - New History record added
2021-12-10 12:12:25.985 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:12:25.985 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:12:25.988 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.845 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:20.933 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.940 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:20.948 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.950 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:20.955 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.955 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:20.961 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.961 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:20.967 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:20.995 [main] INFO  org.example.App - {"id":1639127660951,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:20","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:14:21.201 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:21.230 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:21.234 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:21.247 [main] INFO  org.example.App - New History record added
2021-12-10 12:14:21.247 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:14:21.247 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:21.256 [main] INFO  org.example.App - All records were added
2021-12-10 12:14:21.257 [main] INFO  org.example.App - {"id":1639127661249,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:21","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:14:21.259 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:21.267 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:21.267 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:21.268 [main] INFO  org.example.App - New History record added
2021-12-10 12:14:21.271 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:21.273 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:14:21.273 [main] INFO  org.example.App - {"id":1639127661271,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:21","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1638871430801,\"name\":\"Ahalab\",\"surname\":\"surname3\"}","status":"SUCCESS"}
2021-12-10 12:14:21.276 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:21.283 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:21.283 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:21.284 [main] INFO  org.example.App - New History record added
2021-12-10 12:14:21.284 [main] INFO  org.example.App - {"id":1639127660937,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:20","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:14:21.286 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:21.316 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:21.316 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:21.317 [main] INFO  org.example.App - New History record added
2021-12-10 12:14:21.318 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:14:21.318 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:21.321 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:21.323 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:21.326 [main] INFO  org.example.App - Records were selected
2021-12-10 12:14:21.327 [main] INFO  org.example.App - {"id":1639127661326,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:21","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:14:21.329 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:21.337 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:21.337 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:21.338 [main] INFO  org.example.App - New History record added
2021-12-10 12:14:21.339 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:14:54.037 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:14:54.115 [main] INFO  org.example.App - All records were added
2021-12-10 12:14:54.138 [main] INFO  org.example.App - {"id":1639127694029,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:14:54","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:14:54.327 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:14:54.381 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:14:54.384 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:14:54.398 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:03.440 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.520 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:03.528 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.538 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:03.539 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.546 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:03.547 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.556 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:03.557 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.564 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:03.590 [main] INFO  org.example.App - {"id":1639127703540,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:03","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:15:03.793 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:03.833 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:03.836 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:03.849 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:03.849 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:15:03.849 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.858 [main] INFO  org.example.App - All records were added
2021-12-10 12:15:03.859 [main] INFO  org.example.App - {"id":1639127703851,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:03","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:15:03.861 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:03.868 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:03.868 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:03.869 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:03.871 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.874 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:15:03.874 [main] INFO  org.example.App - {"id":1639127703872,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:03","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1639127693616,\"name\":\"Ahalab\",\"surname\":\"surname1\"}","status":"SUCCESS"}
2021-12-10 12:15:03.876 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:03.912 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:03.912 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:03.913 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:03.914 [main] INFO  org.example.App - {"id":1639127703523,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:03","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:15:03.916 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:03.923 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:03.923 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:03.924 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:03.925 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:15:03.925 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:03.929 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.110 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.182 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.191 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.198 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.199 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.205 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.205 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.212 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.213 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.221 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.244 [main] INFO  org.example.App - {"id":1639127729200,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:29","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:15:29.425 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:29.454 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:29.456 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:29.468 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:29.469 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:15:29.469 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.477 [main] INFO  org.example.App - All records were added
2021-12-10 12:15:29.478 [main] INFO  org.example.App - {"id":1639127729471,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:29","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:15:29.480 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:29.489 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:29.490 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:29.491 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:29.493 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.496 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:15:29.496 [main] INFO  org.example.App - {"id":1639127729494,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:29","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1639127693616,\"name\":\"Ahalab\",\"surname\":\"surname2\"}","status":"SUCCESS"}
2021-12-10 12:15:29.499 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:29.525 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:29.525 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:29.526 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:29.526 [main] INFO  org.example.App - {"id":1639127729186,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:29","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:15:29.528 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:29.535 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:29.535 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:29.536 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:29.536 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:15:29.537 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.540 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.541 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:15:29.544 [main] INFO  org.example.App - Records were selected
2021-12-10 12:15:29.545 [main] INFO  org.example.App - {"id":1639127729545,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:15:29","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:15:29.546 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:15:29.552 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:15:29.553 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:15:29.554 [main] INFO  org.example.App - New History record added
2021-12-10 12:15:29.554 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:16:08.192 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.283 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.290 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.298 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.299 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.305 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.306 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.313 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.313 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.319 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.345 [main] INFO  org.example.App - {"id":1639127768300,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:16:08","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:16:08.547 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:16:08.579 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:16:08.581 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:16:08.593 [main] INFO  org.example.App - New History record added
2021-12-10 12:16:08.594 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:16:08.594 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.603 [main] INFO  org.example.App - All records were added
2021-12-10 12:16:08.603 [main] INFO  org.example.App - {"id":1639127768596,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:16:08","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:16:08.606 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:16:08.614 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:16:08.614 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:16:08.615 [main] INFO  org.example.App - New History record added
2021-12-10 12:16:08.617 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.620 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:16:08.620 [main] INFO  org.example.App - {"id":1639127768618,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:16:08","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1639127693617,\"name\":\"Ahalab\",\"surname\":\"surname3\"}","status":"SUCCESS"}
2021-12-10 12:16:08.622 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:16:08.629 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:16:08.629 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:16:08.630 [main] INFO  org.example.App - New History record added
2021-12-10 12:16:08.631 [main] INFO  org.example.App - {"id":1639127768286,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:16:08","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:16:08.632 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:16:08.639 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:16:08.639 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:16:08.640 [main] INFO  org.example.App - New History record added
2021-12-10 12:16:08.640 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:16:08.640 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.643 [main] INFO  org.example.App - Records were selected
2021-12-10 12:16:08.644 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:16:08.647 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.604 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:58.694 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.701 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:58.708 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.709 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:58.715 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.715 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:58.721 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.721 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:58.728 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:58.754 [main] INFO  org.example.App - {"id":1639127998710,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:19:58","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 12:19:58.953 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:19:58.985 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:19:58.988 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:19:59.001 [main] INFO  org.example.App - New History record added
2021-12-10 12:19:59.001 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 12:19:59.001 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:59.013 [main] INFO  org.example.App - All records were added
2021-12-10 12:19:59.014 [main] INFO  org.example.App - {"id":1639127999003,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:19:59","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 12:19:59.016 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:19:59.028 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:19:59.028 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:19:59.029 [main] INFO  org.example.App - New History record added
2021-12-10 12:19:59.032 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:59.034 [main] INFO  org.example.App - Trainer was added
2021-12-10 12:19:59.035 [main] INFO  org.example.App - {"id":1639127999033,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:19:59","actor":"system","methodName":"createNewTrainer","bean":"{\"id\":1639127693618,\"name\":\"Ahalab\",\"surname\":\"surname4\"}","status":"SUCCESS"}
2021-12-10 12:19:59.038 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:19:59.051 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:19:59.051 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:19:59.052 [main] INFO  org.example.App - New History record added
2021-12-10 12:19:59.052 [main] INFO  org.example.App - {"id":1639127998698,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:19:58","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:19:59.054 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:19:59.061 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:19:59.062 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:19:59.062 [main] INFO  org.example.App - New History record added
2021-12-10 12:19:59.063 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:19:59.063 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:59.067 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:59.068 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:19:59.072 [main] INFO  org.example.App - Records were selected
2021-12-10 12:19:59.072 [main] ERROR org.example.App - java.util.NoSuchElementExceptionNo value present
2021-12-10 12:26:10.116 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:10.210 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:10.218 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:10.228 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:10.257 [main] INFO  org.example.App - {"id":1639128370214,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:26:10","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:26:10.492 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:26:10.534 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:26:10.538 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:26:10.559 [main] INFO  org.example.App - New History record added
2021-12-10 12:26:10.559 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:26:10.559 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:10.579 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:24.178 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:24.266 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:24.274 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:24.283 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:24.308 [main] INFO  org.example.App - {"id":1639128384270,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:26:24","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:26:24.496 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:26:24.529 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:26:24.532 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:26:24.546 [main] INFO  org.example.App - New History record added
2021-12-10 12:26:24.546 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:26:24.546 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:24.559 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:24.560 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:26:24.564 [main] INFO  org.example.App - Records were selected
2021-12-10 12:26:24.564 [main] ERROR org.example.App - java.util.NoSuchElementExceptionNo value present
2021-12-10 12:27:00.689 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:27:00.774 [main] INFO  org.example.App - Records were selected
2021-12-10 12:27:00.780 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:27:00.787 [main] INFO  org.example.App - Records were selected
2021-12-10 12:27:00.816 [main] INFO  org.example.App - {"id":1639128420777,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:27:00","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:27:01.010 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:27:01.045 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:27:01.048 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:27:01.061 [main] INFO  org.example.App - New History record added
2021-12-10 12:27:01.061 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:27:01.061 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:27:01.071 [main] INFO  org.example.App - Records were selected
2021-12-10 12:27:01.072 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:27:01.076 [main] INFO  org.example.App - Records were selected
2021-12-10 12:29:26.231 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:29:26.325 [main] INFO  org.example.App - Records were selected
2021-12-10 12:29:26.333 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:29:26.339 [main] INFO  org.example.App - Records were selected
2021-12-10 12:29:26.363 [main] INFO  org.example.App - {"id":1639128566329,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 12:29:26","actor":"system","methodName":"updateTrainer","status":"SUCCESS"}
2021-12-10 12:29:26.561 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 12:29:26.606 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 12:29:26.609 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 12:29:26.621 [main] INFO  org.example.App - New History record added
2021-12-10 12:29:26.622 [main] DEBUG org.example.App - Trainer updated
2021-12-10 12:29:26.622 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:29:26.635 [main] INFO  org.example.App - Records were selected
2021-12-10 12:29:26.636 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 12:29:26.641 [main] INFO  org.example.App - Records were selected
2021-12-10 12:29:26.642 [main] ERROR org.example.App - java.util.NoSuchElementExceptionNo value present
2021-12-10 14:20:37.361 [main] INFO  org.example.App - Created new CSV file: Client
2021-12-10 14:20:37.364 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:20:37.452 [main] INFO  org.example.App - Client was added
2021-12-10 14:20:37.452 [main] INFO  org.example.App - {"id":1639135237319,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:20:37","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"id\":1639135236675,\"name\":\"Alex\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:20:37.793 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:20:38.251 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:20:38.255 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:20:38.282 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:32.876 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:23:32.952 [main] INFO  org.example.App - Client was added
2021-12-10 14:23:32.953 [main] INFO  org.example.App - {"id":1639135412837,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:23:32","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"id\":1639135412294,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:23:33.159 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:23:33.206 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:23:33.210 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:23:33.224 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:33.230 [main] INFO  org.example.App - Created new CSV file: Workout
2021-12-10 14:23:33.230 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:23:33.241 [main] INFO  org.example.App - Workout was added
2021-12-10 14:23:33.242 [main] INFO  org.example.App - {"id":1639135413229,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:23:33","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135413228,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:23:33.245 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:23:33.255 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:23:33.255 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:23:33.256 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:33.257 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:23:33.263 [main] INFO  org.example.App - Workout was added
2021-12-10 14:23:33.264 [main] INFO  org.example.App - {"id":1639135413258,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:23:33","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135413256,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:23:33.266 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:23:33.279 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:23:33.279 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:23:33.282 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:33.283 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:23:33.293 [main] INFO  org.example.App - Workout was added
2021-12-10 14:23:33.293 [main] INFO  org.example.App - {"id":1639135413285,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:23:33","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135413282,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:23:33.305 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:23:33.319 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:23:33.319 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:23:33.321 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:33.324 [main] INFO  org.example.App - Created new CSV file: Program
2021-12-10 14:23:33.325 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:23:33.347 [main] INFO  org.example.App - Program was added
2021-12-10 14:23:33.347 [main] INFO  org.example.App - {"id":1639135413325,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:23:33","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639135413227,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:23:33.350 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:23:33.358 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:23:33.358 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:23:33.360 [main] INFO  org.example.App - New History record added
2021-12-10 14:23:33.360 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:23:33.380 [main] INFO  org.example.App - Records were selected
2021-12-10 14:23:33.381 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:23:33.386 [main] INFO  org.example.App - Records were selected
2021-12-10 14:26:22.447 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:26:22.518 [main] INFO  org.example.App - Client was added
2021-12-10 14:26:22.519 [main] INFO  org.example.App - {"id":1639135582409,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:26:22","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639135581837,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:26:22.755 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:26:22.808 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:26:22.813 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:26:22.832 [main] INFO  org.example.App - New History record added
2021-12-10 14:26:22.838 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:26:22.846 [main] INFO  org.example.App - Workout was added
2021-12-10 14:26:22.847 [main] INFO  org.example.App - {"id":1639135582837,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:26:22","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135582836,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:26:22.850 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:26:22.862 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:26:22.862 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:26:22.863 [main] INFO  org.example.App - New History record added
2021-12-10 14:26:22.864 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:26:22.872 [main] INFO  org.example.App - Workout was added
2021-12-10 14:26:22.873 [main] INFO  org.example.App - {"id":1639135582866,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:26:22","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135582864,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:26:22.876 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:26:22.906 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:26:22.906 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:26:22.907 [main] INFO  org.example.App - New History record added
2021-12-10 14:26:22.908 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:26:22.914 [main] INFO  org.example.App - Workout was added
2021-12-10 14:26:22.915 [main] INFO  org.example.App - {"id":1639135582910,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:26:22","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135582907,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:26:22.929 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:26:22.939 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:26:22.939 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:26:22.941 [main] INFO  org.example.App - New History record added
2021-12-10 14:26:22.944 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:26:22.948 [main] INFO  org.example.App - Program was added
2021-12-10 14:26:22.949 [main] INFO  org.example.App - {"id":1639135582945,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:26:22","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639135582834,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:26:22.952 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:26:22.965 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:26:22.965 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:26:22.966 [main] INFO  org.example.App - New History record added
2021-12-10 14:26:22.967 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:26:22.990 [main] INFO  org.example.App - Records were selected
2021-12-10 14:26:22.992 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:26:22.997 [main] INFO  org.example.App - Records were selected
2021-12-10 14:28:12.586 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:28:12.659 [main] INFO  org.example.App - Client was added
2021-12-10 14:28:12.660 [main] INFO  org.example.App - {"id":1639135692537,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:28:12","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639135691953,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:28:12.958 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:28:13.021 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:28:13.026 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:28:13.043 [main] INFO  org.example.App - New History record added
2021-12-10 14:28:13.047 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:28:13.053 [main] INFO  org.example.App - Workout was added
2021-12-10 14:28:13.053 [main] INFO  org.example.App - {"id":1639135693047,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:28:13","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135693045,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:28:13.056 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:28:13.065 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:28:13.065 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:28:13.066 [main] INFO  org.example.App - New History record added
2021-12-10 14:28:13.067 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:28:13.107 [main] INFO  org.example.App - Workout was added
2021-12-10 14:28:13.107 [main] INFO  org.example.App - {"id":1639135693069,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:28:13","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135693066,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:28:13.111 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:28:13.121 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:28:13.122 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:28:13.123 [main] INFO  org.example.App - New History record added
2021-12-10 14:28:13.124 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:28:13.128 [main] INFO  org.example.App - Workout was added
2021-12-10 14:28:13.129 [main] INFO  org.example.App - {"id":1639135693127,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:28:13","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135693124,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:28:13.132 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:28:13.141 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:28:13.141 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:28:13.142 [main] INFO  org.example.App - New History record added
2021-12-10 14:28:13.144 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:28:13.148 [main] INFO  org.example.App - Program was added
2021-12-10 14:28:13.149 [main] INFO  org.example.App - {"id":1639135693146,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:28:13","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639135693044,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:28:13.152 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:28:13.160 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:28:13.160 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:28:13.162 [main] INFO  org.example.App - New History record added
2021-12-10 14:28:13.162 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:28:13.184 [main] INFO  org.example.App - Records were selected
2021-12-10 14:28:13.186 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:28:13.191 [main] INFO  org.example.App - Records were selected
2021-12-10 14:30:40.362 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:30:40.450 [main] INFO  org.example.App - Client was added
2021-12-10 14:30:40.451 [main] INFO  org.example.App - {"id":1639135840304,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:30:40","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639135839749,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:30:40.722 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:30:40.781 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:30:40.784 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:30:40.803 [main] INFO  org.example.App - New History record added
2021-12-10 14:30:40.807 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:30:40.813 [main] INFO  org.example.App - Workout was added
2021-12-10 14:30:40.814 [main] INFO  org.example.App - {"id":1639135840807,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:30:40","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135840806,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:30:40.817 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:30:40.828 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:30:40.829 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:30:40.830 [main] INFO  org.example.App - New History record added
2021-12-10 14:30:40.832 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:30:40.838 [main] INFO  org.example.App - Workout was added
2021-12-10 14:30:40.839 [main] INFO  org.example.App - {"id":1639135840833,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:30:40","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135840831,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:30:40.841 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:30:40.851 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:30:40.852 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:30:40.853 [main] INFO  org.example.App - New History record added
2021-12-10 14:30:40.854 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:30:40.859 [main] INFO  org.example.App - Workout was added
2021-12-10 14:30:40.860 [main] INFO  org.example.App - {"id":1639135840856,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:30:40","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639135840853,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:30:40.862 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:30:40.871 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:30:40.871 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:30:40.873 [main] INFO  org.example.App - New History record added
2021-12-10 14:30:40.874 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:30:40.880 [main] INFO  org.example.App - Program was added
2021-12-10 14:30:40.880 [main] INFO  org.example.App - {"id":1639135840877,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:30:40","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639135840804,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:30:40.883 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:30:40.892 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:30:40.892 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:30:40.894 [main] INFO  org.example.App - New History record added
2021-12-10 14:30:40.894 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:30:40.921 [main] INFO  org.example.App - Records were selected
2021-12-10 14:30:40.922 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:30:40.932 [main] INFO  org.example.App - Records were selected
2021-12-10 14:50:23.739 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:50:23.828 [main] INFO  org.example.App - Client was added
2021-12-10 14:50:23.829 [main] INFO  org.example.App - {"id":1639137023692,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:50:23","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639137023043,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:50:24.123 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:50:24.173 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:50:24.177 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:50:24.198 [main] INFO  org.example.App - New History record added
2021-12-10 14:50:24.202 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:50:24.210 [main] INFO  org.example.App - Workout was added
2021-12-10 14:50:24.210 [main] INFO  org.example.App - {"id":1639137024202,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:50:24","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137024200,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:50:24.213 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:50:24.225 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:50:24.225 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:50:24.226 [main] INFO  org.example.App - New History record added
2021-12-10 14:50:24.227 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:50:24.232 [main] INFO  org.example.App - Workout was added
2021-12-10 14:50:24.232 [main] INFO  org.example.App - {"id":1639137024228,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:50:24","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137024226,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:50:24.234 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:50:24.245 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:50:24.246 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:50:24.247 [main] INFO  org.example.App - New History record added
2021-12-10 14:50:24.248 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:50:24.271 [main] INFO  org.example.App - Workout was added
2021-12-10 14:50:24.271 [main] INFO  org.example.App - {"id":1639137024250,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:50:24","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137024247,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:50:24.273 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:50:24.299 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:50:24.300 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:50:24.301 [main] INFO  org.example.App - New History record added
2021-12-10 14:50:24.302 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:50:24.306 [main] INFO  org.example.App - Program was added
2021-12-10 14:50:24.307 [main] INFO  org.example.App - {"id":1639137024305,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:50:24","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639137024200,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:50:24.308 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:50:24.317 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:50:24.317 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:50:24.318 [main] INFO  org.example.App - New History record added
2021-12-10 14:50:24.319 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:50:24.342 [main] INFO  org.example.App - Records were selected
2021-12-10 14:50:24.343 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:50:24.349 [main] INFO  org.example.App - Records were selected
2021-12-10 14:52:17.996 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:52:18.105 [main] INFO  org.example.App - Client was added
2021-12-10 14:52:18.107 [main] INFO  org.example.App - {"id":1639137137943,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:52:17","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639137137423,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:52:18.428 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:52:18.484 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:52:18.489 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:52:18.507 [main] INFO  org.example.App - New History record added
2021-12-10 14:52:18.513 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:52:18.519 [main] INFO  org.example.App - Workout was added
2021-12-10 14:52:18.519 [main] INFO  org.example.App - {"id":1639137138512,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:52:18","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137138511,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:52:18.523 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:52:18.535 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:52:18.536 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:52:18.537 [main] INFO  org.example.App - New History record added
2021-12-10 14:52:18.538 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:52:18.544 [main] INFO  org.example.App - Workout was added
2021-12-10 14:52:18.545 [main] INFO  org.example.App - {"id":1639137138540,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:52:18","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137138538,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:52:18.550 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:52:18.561 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:52:18.561 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:52:18.562 [main] INFO  org.example.App - New History record added
2021-12-10 14:52:18.563 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:52:18.567 [main] INFO  org.example.App - Workout was added
2021-12-10 14:52:18.567 [main] INFO  org.example.App - {"id":1639137138565,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:52:18","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137138562,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:52:18.569 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:52:18.578 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:52:18.578 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:52:18.580 [main] INFO  org.example.App - New History record added
2021-12-10 14:52:18.582 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:52:18.588 [main] INFO  org.example.App - Program was added
2021-12-10 14:52:18.588 [main] INFO  org.example.App - {"id":1639137138584,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:52:18","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639137138510,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:52:18.591 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:52:18.600 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:52:18.600 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:52:18.601 [main] INFO  org.example.App - New History record added
2021-12-10 14:52:18.602 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:52:18.625 [main] INFO  org.example.App - Records were selected
2021-12-10 14:52:18.626 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:52:18.632 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:19.928 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.000 [main] INFO  org.example.App - Client was added
2021-12-10 14:58:20.001 [main] INFO  org.example.App - {"id":1639137499888,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:19","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639137499214,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:58:20.191 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.230 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.233 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.248 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.252 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:20.257 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:20.258 [main] INFO  org.example.App - {"id":1639137500252,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137500251,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:20.260 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.269 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.269 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.270 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.270 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:20.275 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:20.275 [main] INFO  org.example.App - {"id":1639137500272,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137500270,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:20.277 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.284 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.284 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.286 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.286 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:20.296 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:20.297 [main] INFO  org.example.App - {"id":1639137500289,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137500286,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:20.298 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.307 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.307 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.308 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.309 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:58:20.313 [main] INFO  org.example.App - Program was added
2021-12-10 14:58:20.313 [main] INFO  org.example.App - {"id":1639137500312,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639137500250,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:58:20.315 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.322 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.322 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.323 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.324 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.341 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.343 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.350 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.350 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.356 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.356 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.362 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.363 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 14:58:20.367 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.368 [main] ERROR org.example.App - java.util.NoSuchElementExceptionNo value present
2021-12-10 14:58:20.368 [main] ERROR org.example.App - Trainer not found
2021-12-10 14:58:20.369 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 14:58:20.372 [main] INFO  org.example.App - Records were selected
2021-12-10 14:58:20.373 [main] INFO  org.example.App - {"id":1639137500368,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 14:58:20.375 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.383 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.383 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.384 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.384 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 14:58:20.385 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 14:58:20.393 [main] INFO  org.example.App - All records were added
2021-12-10 14:58:20.394 [main] INFO  org.example.App - {"id":1639137500392,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 14:58:20.396 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.428 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.428 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.429 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.430 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:20.433 [main] INFO  org.example.App - Client was added
2021-12-10 14:58:20.434 [main] INFO  org.example.App - {"id":1639137500437,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[1639137500250],\"id\":1639137499214,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:58:20.436 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.445 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.445 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.446 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.447 [main] INFO  org.example.App - {"id":1639137500355,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:20","actor":"system","methodName":"updateClient","status":"SUCCESS"}
2021-12-10 14:58:20.448 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:20.457 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:20.457 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:20.458 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:20.458 [main] DEBUG org.example.App - Client updated
2021-12-10 14:58:50.023 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:58:50.100 [main] INFO  org.example.App - Client was added
2021-12-10 14:58:50.101 [main] INFO  org.example.App - {"id":1639137529984,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:49","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639137529509,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:58:50.304 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:50.356 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:50.359 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:50.377 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:50.382 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:50.387 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:50.388 [main] INFO  org.example.App - {"id":1639137530382,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:50","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137530381,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:50.390 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:50.398 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:50.399 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:50.400 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:50.400 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:50.405 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:50.406 [main] INFO  org.example.App - {"id":1639137530402,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:50","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137530400,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:50.408 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:50.416 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:50.416 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:50.418 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:50.418 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:58:50.423 [main] INFO  org.example.App - Workout was added
2021-12-10 14:58:50.423 [main] INFO  org.example.App - {"id":1639137530421,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:50","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137530418,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:58:50.435 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:50.441 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:50.442 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:50.442 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:50.444 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:58:50.447 [main] INFO  org.example.App - Program was added
2021-12-10 14:58:50.448 [main] INFO  org.example.App - {"id":1639137530447,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:58:50","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639137530380,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:58:50.450 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:58:50.456 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:58:50.457 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:58:50.458 [main] INFO  org.example.App - New History record added
2021-12-10 14:58:50.458 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:59:00.060 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 14:59:00.146 [main] INFO  org.example.App - Client was added
2021-12-10 14:59:00.147 [main] INFO  org.example.App - {"id":1639137540011,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:59:00","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639137539521,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 14:59:00.363 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:59:00.399 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:59:00.403 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:59:00.424 [main] INFO  org.example.App - New History record added
2021-12-10 14:59:00.430 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:59:00.438 [main] INFO  org.example.App - Workout was added
2021-12-10 14:59:00.439 [main] INFO  org.example.App - {"id":1639137540430,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:59:00","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137540428,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:59:00.443 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:59:00.455 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:59:00.455 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:59:00.457 [main] INFO  org.example.App - New History record added
2021-12-10 14:59:00.458 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:59:00.487 [main] INFO  org.example.App - Workout was added
2021-12-10 14:59:00.488 [main] INFO  org.example.App - {"id":1639137540459,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:59:00","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137540457,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:59:00.492 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:59:00.502 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:59:00.502 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:59:00.504 [main] INFO  org.example.App - New History record added
2021-12-10 14:59:00.505 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 14:59:00.509 [main] INFO  org.example.App - Workout was added
2021-12-10 14:59:00.509 [main] INFO  org.example.App - {"id":1639137540507,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:59:00","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639137540504,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 14:59:00.519 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:59:00.527 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:59:00.527 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:59:00.528 [main] INFO  org.example.App - New History record added
2021-12-10 14:59:00.531 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 14:59:00.534 [main] INFO  org.example.App - Program was added
2021-12-10 14:59:00.534 [main] INFO  org.example.App - {"id":1639137540533,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 14:59:00","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639137540427,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 14:59:00.536 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 14:59:00.545 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 14:59:00.545 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 14:59:00.546 [main] INFO  org.example.App - New History record added
2021-12-10 14:59:00.546 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:07:43.320 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:07:43.388 [main] INFO  org.example.App - Client was added
2021-12-10 15:07:43.389 [main] INFO  org.example.App - {"id":1639138063282,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:07:43","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639138062809,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 15:07:43.573 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:07:43.606 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:07:43.609 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:07:43.622 [main] INFO  org.example.App - New History record added
2021-12-10 15:07:43.627 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:07:43.633 [main] INFO  org.example.App - Workout was added
2021-12-10 15:07:43.633 [main] INFO  org.example.App - {"id":1639138063627,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:07:43","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138063626,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:07:43.635 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:07:43.643 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:07:43.643 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:07:43.644 [main] INFO  org.example.App - New History record added
2021-12-10 15:07:43.645 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:07:43.649 [main] INFO  org.example.App - Workout was added
2021-12-10 15:07:43.650 [main] INFO  org.example.App - {"id":1639138063646,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:07:43","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138063644,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:07:43.652 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:07:43.662 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:07:43.662 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:07:43.663 [main] INFO  org.example.App - New History record added
2021-12-10 15:07:43.664 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:07:43.668 [main] INFO  org.example.App - Workout was added
2021-12-10 15:07:43.669 [main] INFO  org.example.App - {"id":1639138063666,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:07:43","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138063663,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:07:43.677 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:07:43.684 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:07:43.684 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:07:43.685 [main] INFO  org.example.App - New History record added
2021-12-10 15:07:43.687 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 15:07:43.708 [main] INFO  org.example.App - Program was added
2021-12-10 15:07:43.708 [main] INFO  org.example.App - {"id":1639138063689,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:07:43","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639138063625,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 15:07:43.710 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:07:43.717 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:07:43.717 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:07:43.718 [main] INFO  org.example.App - New History record added
2021-12-10 15:07:43.719 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.175 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.248 [main] INFO  org.example.App - Client was added
2021-12-10 15:08:57.249 [main] INFO  org.example.App - {"id":1639138137138,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639138136681,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 15:08:57.479 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.520 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.523 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.537 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.542 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:08:57.551 [main] INFO  org.example.App - Workout was added
2021-12-10 15:08:57.552 [main] INFO  org.example.App - {"id":1639138137542,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138137540,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:08:57.554 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.564 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.564 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.565 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.566 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:08:57.572 [main] INFO  org.example.App - Workout was added
2021-12-10 15:08:57.573 [main] INFO  org.example.App - {"id":1639138137567,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138137565,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:08:57.575 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.583 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.584 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.585 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.586 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:08:57.592 [main] INFO  org.example.App - Workout was added
2021-12-10 15:08:57.593 [main] INFO  org.example.App - {"id":1639138137588,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138137585,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:08:57.602 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.611 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.611 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.612 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.614 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 15:08:57.619 [main] INFO  org.example.App - Program was added
2021-12-10 15:08:57.619 [main] INFO  org.example.App - {"id":1639138137617,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639138137539,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 15:08:57.622 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.629 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.629 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.631 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.631 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.653 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.655 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.661 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.662 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.668 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.668 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.673 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.674 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 15:08:57.680 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.680 [main] ERROR org.example.App - java.util.NoSuchElementExceptionNo value present
2021-12-10 15:08:57.680 [main] ERROR org.example.App - Trainer not found
2021-12-10 15:08:57.680 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 15:08:57.684 [main] INFO  org.example.App - Records were selected
2021-12-10 15:08:57.685 [main] INFO  org.example.App - {"id":1639138137679,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"deleteTrainerById","status":"SUCCESS"}
2021-12-10 15:08:57.687 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.695 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.695 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.696 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.696 [main] DEBUG org.example.App - Trainer deleted
2021-12-10 15:08:57.696 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Trainer.csv
2021-12-10 15:08:57.705 [main] INFO  org.example.App - All records were added
2021-12-10 15:08:57.705 [main] INFO  org.example.App - {"id":1639138137703,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"saveRecords","status":"SUCCESS"}
2021-12-10 15:08:57.707 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.715 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.715 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.716 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.717 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:08:57.721 [main] INFO  org.example.App - Client was added
2021-12-10 15:08:57.721 [main] INFO  org.example.App - {"id":1639138137724,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[1639138137539],\"id\":1639138136681,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 15:08:57.723 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.759 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.759 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.760 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.760 [main] INFO  org.example.App - {"id":1639138137666,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:08:57","actor":"system","methodName":"updateClient","status":"SUCCESS"}
2021-12-10 15:08:57.762 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:08:57.769 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:08:57.769 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:08:57.770 [main] INFO  org.example.App - New History record added
2021-12-10 15:08:57.771 [main] DEBUG org.example.App - Client updated
2021-12-10 15:09:52.952 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:09:53.026 [main] INFO  org.example.App - Client was added
2021-12-10 15:09:53.027 [main] INFO  org.example.App - {"id":1639138192908,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:09:52","actor":"system","methodName":"createNewClient","bean":"{\"age\":12,\"weight\":12,\"height\":12,\"programs\":[],\"id\":1639138192365,\"name\":\"Dave\",\"surname\":\"Mclovin\"}","status":"SUCCESS"}
2021-12-10 15:09:53.225 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:09:53.280 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:09:53.283 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:09:53.301 [main] INFO  org.example.App - New History record added
2021-12-10 15:09:53.305 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:09:53.318 [main] INFO  org.example.App - Workout was added
2021-12-10 15:09:53.319 [main] INFO  org.example.App - {"id":1639138193305,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:09:53","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138193304,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:09:53.321 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:09:53.381 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:09:53.382 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:09:53.383 [main] INFO  org.example.App - New History record added
2021-12-10 15:09:53.384 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:09:53.417 [main] INFO  org.example.App - Workout was added
2021-12-10 15:09:53.418 [main] INFO  org.example.App - {"id":1639138193385,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:09:53","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138193383,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:09:53.423 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:09:53.489 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:09:53.490 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:09:53.492 [main] INFO  org.example.App - New History record added
2021-12-10 15:09:53.494 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Workout.csv
2021-12-10 15:09:53.508 [main] INFO  org.example.App - Workout was added
2021-12-10 15:09:53.509 [main] INFO  org.example.App - {"id":1639138193496,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:09:53","actor":"system","methodName":"createNewWorkout","bean":"{\"id\":1639138193493,\"exercises\":[],\"weights\":[],\"rounds\":[],\"repetitions\":[]}","status":"SUCCESS"}
2021-12-10 15:09:53.511 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:09:53.518 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:09:53.518 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:09:53.520 [main] INFO  org.example.App - New History record added
2021-12-10 15:09:53.521 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 15:09:53.524 [main] INFO  org.example.App - Program was added
2021-12-10 15:09:53.525 [main] INFO  org.example.App - {"id":1639138193524,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:09:53","actor":"system","methodName":"createNewProgram","bean":"{\"id\":1639138193303,\"workouts\":[null,null,null],\"durationInWeeks\":3,\"workoutsPerWeek\":3,\"description\":\"\",\"type\":\"FLEXIBILITY\"}","status":"SUCCESS"}
2021-12-10 15:09:53.526 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:09:53.533 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:09:53.534 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:09:53.534 [main] INFO  org.example.App - New History record added
2021-12-10 15:09:53.535 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:10:53.038 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:17:02.473 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 15:17:02.564 [main] INFO  org.example.App - Records were selected
2021-12-10 15:18:15.259 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Program.csv
2021-12-10 15:18:15.345 [main] INFO  org.example.App - Records were selected
2021-12-10 15:18:15.379 [main] INFO  org.example.App - CSV PATH is :./src/main/resources/CSV/Client.csv
2021-12-10 15:18:15.392 [main] INFO  org.example.App - Client was added
2021-12-10 15:18:15.392 [main] INFO  org.example.App - {"id":1639138695348,"className":"class org.example.DataProviders.DataProviderCsv","createdDate":"10/12/2021 15:18:15","actor":"system","methodName":"createNewClient","bean":"{\"age\":0,\"weight\":0,\"height\":0,\"programs\":[1639135413227,1639135582834,1639135693044,1639135840804,1639137024200,1639137138510,1639137500250,1639137530380,1639137540427,1639138063625,1639138137539,1639138193303],\"id\":1639138695345}","status":"SUCCESS"}
2021-12-10 15:18:15.623 [main] INFO  org.example.App - Connected to MongoDB
2021-12-10 15:18:15.661 [main] ERROR org.example.App - com.mongodb.MongoCommandExceptionCommand failed with error 48: 'Collection already exists. NS: myMongoDb.HistoryContent' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Collection already exists. NS: myMongoDb.HistoryContent", "code" : 48, "codeName" : "NamespaceExists" }
2021-12-10 15:18:15.666 [main] INFO  org.example.App - MongoDB collection received
2021-12-10 15:18:15.680 [main] INFO  org.example.App - New History record added
